name: Steps em sequencia

on:
  push:
    branches:
      - main

jobs:
  info-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Obter Data Atual (São Paulo)
        run: TZ="America/Sao_Paulo" date +"%Y-%m-%d"

      - name: Obter Autor do Commit
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "O autor do commit é: $AUTHOR"

      - name: Contar Arquivos HTML
        run: |
          TOTAL_HTML=$(find . -type f -name "*.html" | wc -l)
          echo "Total de arquivos HTML: $TOTAL_HTML"

      - name: Contar Arquivos CSS
        run: |
          TOTAL_CSS=$(find . -type f -name "*.css" | wc -l)
          echo "Total de arquivos CSS: $TOTAL_CSS"

      - name: Contar Arquivos JS
        run: |
          TOTAL_JS=$(find . -type f -name "*.js" | wc -l)
          echo "Total de arquivos JS: $TOTAL_JS"
