name: Calcular 2+2

on:
  push:
    branches: [main]
    
jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout code
         uses: actions/checkout@v3

      -  name: Calcular e mostrar 2+2
         run: echo "O resultado de 2+2 é: $((2+2))"
