name: Listar Arquivos

on:
  push:
    branches: [main]
    
jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout code
         uses: actions/checkout@v3

      -  name: Listar arquivos no terminal
         run: ls -l
