name: Rodar apenas aos sabados

on:
  schedule:
    # Continua rodando todo dia à meia-noite UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  job-de-sabado: # Nome do job alterado
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4

      - name: 2. Verificar se hoje é sábado
        run: |
          # Pega o dia da semana (1=Seg, 6=Sab, 7=Dom) usando o fuso de SP
          DIA_DA_SEMANA=$(TZ="America/Sao_Paulo" date +%u)

          # Verifica se o dia NÃO é 6 (Sábado)
          if [[ "$DIA_DA_SEMANA" -ne 6 ]]; then
            echo "Hoje não é Sábado (Dia $DIA_DA_SEMANA em SP). Encerrando."
            exit 0
          fi
          
          # Se o script chegou até aqui, é porque é Sábado
          echo "É Sábado. Iniciando o processo..."
          
          # ---------------------------------------------
          # COLOQUE AQUI OS COMANDOS DO SÁBADO
          # ---------------------------------------------
